CREATE TABLE IF NOT EXISTS rentalItem (
    id INT generated by default as identity PRIMARY KEY,
    serialNo VARCHAR(15) NOT NULL,
    itemName VARCHAR(45)
);

MERGE INTO rentalItem VALUES (1, 'A0001', 'レンタル品1号');
MERGE INTO rentalItem VALUES (2, 'A0002', 'レンタル品2号');
MERGE INTO rentalItem VALUES (3, 'A0003', 'レンタル品3号');
MERGE INTO rentalItem VALUES (4, 'A0004', 'レンタル品4号');
