DELETE FROM RENTAL_ITEM_ENTITY;

INSERT INTO RENTAL_ITEM_ENTITY VALUES (1, 'A0001', 'レンタル品1号');
INSERT INTO RENTAL_ITEM_ENTITY VALUES (2, 'A0002', 'レンタル品2号');
INSERT INTO RENTAL_ITEM_ENTITY VALUES (3, 'A0003', 'レンタル品3号');
INSERT INTO RENTAL_ITEM_ENTITY VALUES (4, 'A0004', 'レンタル品4号');
