CREATE SEQUENCE IF NOT EXISTS RENTALITEM_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS RENTAL_ITEM_ENTITY (
    ID INT PRIMARY KEY,
    SERIAL_NO VARCHAR(15) NOT NULL,
    ITEM_NAME VARCHAR(45)
);
